---

- name: Build Docker Image
  hosts: all
  become: yes
  tasks:

    - name: Copy Dockerimage
      copy:
        src: "{{ playbook_dir }}/../Dockerimages/{{ dockerimage }}"
        dest: /home/machine/{{ dockerimage }}

    - name: Build Docker image
      docker_image:
        name: "{{ dockerimage }}"
        build: 
          path: .
        dockerfile: "/home/machine/{{ dockerimage }}"
        state: present

    - name: Delete dockerfile
      shell: "rm {{ playbook_dir }}/../Dockerimages/{{ dockerimage }}"
