-- MySQL Script generated by MySQL Workbench
-- Wed Aug 21 21:26:34 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema diplomski
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `diplomski` ;

-- -----------------------------------------------------
-- Schema diplomski
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `diplomski` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `diplomski` ;

-- -----------------------------------------------------
-- Table `diplomski`.`machines`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `diplomski`.`machines` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NULL DEFAULT NULL,
  `hostname` VARCHAR(50) NULL DEFAULT NULL,
  `ipv4` VARCHAR(50) NULL DEFAULT NULL,
  `ipv6` VARCHAR(50) NULL DEFAULT NULL,
  `port` INT NULL DEFAULT '0',
  `posx` INT NULL DEFAULT '-1',
  `posy` INT NULL DEFAULT '-1',
  `roomId` INT NOT NULL DEFAULT '-1',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `diplomski`.`rooms`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `diplomski`.`rooms` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `diplomski`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `diplomski`.`users` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(300) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
